Theme: jekyll-theme-minimal
Title: Welcome to John Ushigome's Professional Portolio! 
Professional Headshot: ![ProfessionalHeadshot](https://user-images.githubusercontent.com/77191762/104110545-c2a5cc00-527c-11eb-950d-5563d98de505.JPG)
Description: I am currently a senior at San Jose State University majoring in Management Information Systems. I am looking to attend graduate school this coming Fall 2021, while also searching for work experience. 
