theme: jekyll-theme-slate
title: Welcome to John Ushigome's Professional Portolio!
description: I am currently a senior at San Jose State University majoring in Management Information Systems. I am looking to attend graduate school this coming Fall 2021, while also exploring work opportunities. 
